// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwSmZGKLazkvp0wWgZ8yewZbi0bAS35Cc',
    appId: '1:672997253234:web:d926589d97881a0eda22eb',
    messagingSenderId: '672997253234',
    projectId: 'chatter-box-007',
    authDomain: 'chatter-box-007.firebaseapp.com',
    storageBucket: 'chatter-box-007.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_A2whpXzuf4OvyWbG33gYAkcR07Zstc',
    appId: '1:672997253234:android:d6d99657a63218f8da22eb',
    messagingSenderId: '672997253234',
    projectId: 'chatter-box-007',
    storageBucket: 'chatter-box-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqAndtnbDFkogvNTDdOUyWtuCQlYY22q8',
    appId: '1:672997253234:ios:dffef3af6a9924c9da22eb',
    messagingSenderId: '672997253234',
    projectId: 'chatter-box-007',
    storageBucket: 'chatter-box-007.appspot.com',
    iosClientId: '672997253234-16tsaod95cgpofg4ta5meh1cd3sp86a9.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterBox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqAndtnbDFkogvNTDdOUyWtuCQlYY22q8',
    appId: '1:672997253234:ios:5d6cfdf9dac44acdda22eb',
    messagingSenderId: '672997253234',
    projectId: 'chatter-box-007',
    storageBucket: 'chatter-box-007.appspot.com',
    iosClientId: '672997253234-t02cgpjbeqn2ngq4updc948v4oe4q1dt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatterBox.RunnerTests',
  );
}
